name: pro-actions

on:
  push:
    branches: [ "Restructuracion" ]
  pull_request:
    branches: [ "Restructuracion" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Production
      run: dotnet test --no-build --verbosity normal    
    - name: ls dir
      run: ls ./Gestion_Administrativa_Api/bin
    - uses: docker/login-action@v2.1.0
      if: ${{ github.event_name == 'push' }}
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
    - uses: docker/setup-buildx-action@v2.2.1
      if: ${{ github.event_name == 'push' }}
    - uses: docker/build-push-action@v3.2.0
      if: ${{ github.event_name == 'push' }}
      env:
        ASPNETCORE_ENVIRONMENT: Production
      with:
        context: ./Gestion_Administrativa_Api
        push: true
        tags: registry.digitalocean.com/intuitosa/Gestion-Administrativa-Api:${{ github.sha }}, registry.digitalocean.com/intuitosa/Gestion-Administrativa-Api:latest-pro
    - name: Image digest
      if: ${{ github.event_name == 'push' }}
      run: echo ${{ steps.docker_build.outputs.digest }}
